apiVersion: apps/v1
kind: Deployment
metadata:
  name: gataria-backend-catalog
  labels:
    app: gataria-backend-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gataria-backend-catalog
  template:
    metadata:
      labels:
        app: gataria-backend-catalog
    spec:
      containers:
        - name: gataria-backend-catalog
          image: fernandindtjr/gataria-backend-catalog:dev
          ports:
            - containerPort: 3010
          env:
            - name: MONGO_URL
              value: "mongodb+srv://admin:admin@mongodb.k8ovxdo.mongodb.net/?appName=mongodb"
            - name: MONGODATABASE
              value: "dev"
